### ISSUE TITLE
API keys will be deprecated by the end of January 2024

### ISSUE THREAD

**Issue by shubham012345** [joeartsea/node-red-contrib-airtable#17]
Hi,

Below is warning getting from airtable team.

**API keys will be deprecated by the end of January 2024
After this date, API keys will stop working and you will have to migrate to personal access tokens. Personal access tokens allow you to more securely grant API access to Airtable data**

Airtable Link - https://support.airtable.com/docs/airtable-api-key-deprecation-notice

Basically we are using airtable api key in Node-RED for authorization as in future API keys will be deprecated.

**So, how to pass personal access tokens in airtable node? In airtable node there is option to pass only api-key there is no option to pass personal token.**
![image](https://github.com/joeartsea/node-red-contrib-airtable/assets/49302661/58491b82-9394-40fd-9919-03e6098eb60d)

Thanks
Shubham Kaushik

**Comment by joeartsea** [comment]
@shubham012345 If you enter a personal access token in the current api key field, it will work correctly. I have already changed the api key to personal access token in one of my projects.
I have not supported OAuth for now because I don't think it is necessary for Node-RED use cases.
Is there a problem with this understanding?

**Comment by shubham012345** [comment]
@joeartsea Thanks a lot, Got It
